config/routes.rb
ChinazoParty::Application.routes.draw do
  #get "home/index"
  #root :to => 'home#index'
  #get "chinazos/new"
  #root :to => 'chinazos#new'
  #get "chinazos/create"
  #root :to => 'chinazos#create'
  #get "chinazos" => "chinazos#index"
  #post "chinazos" => "chinazos#create"
  #get "chinazos/:id" => 'chinazos#show', as: :chinazo
  #get "chinazos/:id/edit" => 'chinazos#edit'
  #put "chinazos/:id" => "chinazos#update"
  #delete "chinazos/:id" => "chinazos#destroy"
  resources :chinazos
  root to: "home#index"
  get "login" => 'user#login'
  get "user/registro" => 'user#registro'
  post "user/authenticate" => "user#authenticate"
  get "user/:login" => "user#show"
  post "user/create" => "user#create"
  get "ajax/users" => "ajax#users"
  post "vote/new" => "vote#new"
  post "comentarios" => "comentario#create"
  get "comentarios/:chinazo_id" => "comentario#listPartial"
  get "puntajes" => "chinazos#buscarPuntos"
  get "comentarios" => "comentario#ultimosComentarios"
  get "ultimos" => "chinazos#ultimos"
end

app/models/chinazo.rb
class Chinazo < ActiveRecord::Base
	has_many :comentario
	attr_accessor :acusador, :puntos, :cantidad_comentarios
	attr_accessible :descripcion, :nombre
	validates :nombre, presence: true, length: { minimum: 3 }
	#before_save :serUserId

	def puntos
		@puntos = Vote.sum(:value,  :conditions =>"chinazos_id = #{id}")
		if @puntos.nil?
			self.puntos = 0
		else
			self.puntos = @puntos	
		end
	end

	def acusador
		User.find(users_id).nombre if users_id
	end

	def cantidad_comentarios
		Comentario.where("chinazos_id = #{id}").count if self.id
	end

	def puntos_by_user(user_id)
	    #ActiveRecord::Base.logger.debug "Comprobando votos usuario: #{user_id}" 
	    @vote = Vote.where("chinazos_id = ? and users_id= ?", id, user_id).first
		if @vote
			@vote.value if self.id
		else
			return 0
		end
	end
end

app/controllers/chinazos_controller.rb
class ChinazosController < ApplicationController
	def new
		@chinazo = Chinazo.new
	end

	def create
		if session[:current_user]
			@chinazo = Chinazo.new(params[:chinazo])
			@chinazo.users_id = session[:current_user_id]
			if @chinazo.save
				redirect_to action: :show, id: @chinazo.id
			end
		else
			@chinazo = Chinazo.new
			flash[:errors] =  "Debes iniciar session para registrar un chinazo"
				render 'new'
		end
	end

	def update
		@chinazo = Chinazo.find(params[:id])
		if session[:current_user] && @chinazo.update_attributes(params[:chinazo])
			redirect_to action: :show, id: @chinazo.id
		else
			render 'edit';
		end
	end

	def show
		if params[:id].to_i != 0
			@chinazo = Chinazo.find(params[:id])
			@comentarios = Comentario.where('chinazos_id = ?', params[:id]).sort!{|a,b| b.updated_at <=> a.updated_at}
		end
	end

	def ultimos
		page = (params[:page] ||= 1).to_i
	    items_per_page = 10

		@chinazos = Chinazo.all(:order => "created_at desc")
		@chinazos = Kaminari.paginate_array(@chinazos).page(page).per(items_per_page)

		@puntajes = 
		Vote.connection.select_all("select chinazos.nombre, sum(puntos.puntos) as puntos from  (select chinazos_id, sum(value) as puntos from votes group by chinazos_id) puntos join chinazos on puntos.chinazos_id = chinazos.id group by chinazos.nombre order by puntos desc limit 10")

		@comentarios = Comentario.all(:order => "created_at desc",
									  :limit => "10")
		render 'index'
	end
	
	def index
		#inicio las variables la paginación
		page = (params[:page] ||= 1).to_i
	    items_per_page = 10

		@chinazos = (Chinazo.all.sort!{|a,b| b.puntos <=> a.puntos})
		@chinazos = Kaminari.paginate_array(@chinazos).page(page).per(items_per_page)

		@puntajes = 
		Vote.connection.select_all("select chinazos.nombre, sum(puntos.puntos) as puntos from  (select chinazos_id, sum(value) as puntos from votes group by chinazos_id) puntos join chinazos on puntos.chinazos_id = chinazos.id group by chinazos.nombre order by puntos desc limit 10")

		@comentarios = Comentario.all(:order => "created_at desc",
									  :limit => "10")
	end

	def edit
		@chinazo = Chinazo.find(params[:id])
	end

	def destroy
		@chinazo = Chinazo.find(params[:id])
		@chinazo.destroy

		redirect_to action: :index
	end
end

app/helpers/chinazos_helper.rb
module ChinazosHelper
end

app/views/chinazos/_buscarPuntos.html.erb
<% @count = 1
@puntajes.each do |pato| %>
	<div class="puntaje_linea"><span class="puntaje_puntos"><%= pato["puntos"] %></span> - <a href='/user/<%= pato["nombre"] %>' class="default-link"><span class="puntaje_nombre"><%= pato["nombre"] %></span></a></div>
<% @count = @count+1
end %>

app/views/chinazos/_chinazos.html.erb
<% @cont = 1  
   @chinazos.each do |chinazo|  %>
	<div class="box level_<%= @cont %>">
		<div class="puntajeAdorno"><%= chinazo.puntos %> Pts.</div>
		<div class="rightGroup">
			<div class="chinazoWrap">
				<span id="titulo"><%= chinazo.nombre %>:</span>
				<span class="contenido"><%= auto_link(chinazo.descripcion) { | each | each[/\.(jpg|gif|png|bmp|tif)$/] ? %Q{<img src="#{each}" width="160px" class="embeddedImage" /> } : each } %></span>
			</div>
			<div>
				<%= link_to "ver mas...", action: :show, id: chinazo.id , controller: :chinazos %>
				<% if session[:current_user_id] == chinazo.users_id %>
				<%= link_to 'Eliminar', { action: :destroy, id: chinazo.id, controller: :chinazos }, method: :delete, data: { confirm: 'Seguro?' } %>
				<% end %>
				<div class="cantidadChinazos"><%= chinazo.cantidad_comentarios %> <span>comentarios</span></div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
<% @cont = @cont + 1
end %>

app/views/chinazos/_form.html.erb
<% if flash[:errors].nil? == false %>
	<div class='errors'><%= flash[:errors] %></div>
<% end %>
<%= form_for @chinazo do |f| %>
<% if @chinazo.errors.any? %>
	<div id="ErrorText">
		<h2><%= pluralize(@chinazo.errors.count, "error") %> ha evitado que se guarde éste chinazo: </h2>
		<ul>
			<% @chinazo.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>
	<p>
		<%= f.label :nombre, "Quién se lo lanzó" %><br/>
		<%= f.text_field :nombre %>
	</p>
	<p>
		<%= f.label :descripcion, "Qué dijo?" %><br/>
		<%= f.text_area :descripcion %>
	</p>
	<p>
    	<%= f.submit %>
 	</p>
<% end %>

app/views/chinazos/_indexComentarios.html.erb
<% @count = 1
@comentarios.each do |comentario| %>
	<div class="comentario_linea"><a class="default-link" href="/chinazos/<%= comentario.chinazos_id %>"><span class="comentario_texto"><%  @Vinculos = comentario.comentario.scan(/((mailto\:|(news|(ht|f)tp(s?))\:\/\/){1}\S+)/i) %>
		 <% if @Vinculos.nil? || @Vinculos.size == 0 %>
		 	<%= comentario.comentario %>
		 <% else %>
		        <% @comentario = comentario.comentario %>
			<% @Vinculos.each do | vinculo | %>
				<% @comentario.sub! vinculo[0], '' %>
		 	<% end %>
			<%= @comentario %>
			<% @Vinculos.each do | vinculo | %>
				<% if vinculo[0].match(/\.(jpg|gif|png|bmp|tif)$/) %>
					<img <%= "src='#{vinculo[0]}'" %> width='100px' class='embeddedImage' />
				<% end %>
		 	<% end %> 
		 <% end %>	
	</span></a></div>
<% @count = @count+1
end %>

app/views/chinazos/edit.html.erb
<h1>Acomodar</h1>
<%= render 'form' %>
<%= link_to "Cancelar", action: :index %>

app/views/chinazos/index.html.erb
<div class="wrapper">
	<div class="header">
		<%= render "home/header" %>
		<div class="header_wrapper">
			<img class="logo" src="assets/charlie.png"/>
			<h1 class="pageTitle">Chinazómetro</h1>
			<div class="h3">El top de los chinazos</div>
			<div id="acusar_link"><a href="/chinazos/new">Acusa un Chinazo</a></div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="firstColumn">
		<div class="colunm_wrapper">
			<div class="table_title">Anuncios</div>
				Para reportar un chinazo haz clic en acusar chinazo, para votar ingresa en la opción "ver mas" del chinazo a juzgar. Debes estar registrado para poder reportar, valorar o comentar chinazos.	
			</div>
		</div>
	<div class="mainContent">
		<div class="clear"></div>
		<div id="container">
			<%= render "chinazos" %>
		</div>
		<%= paginate @chinazos %>
	</div>
	<div class="column_wrapper">
		<div class="buscador">
			<%= label_tag :nombre, "Buscar" %><br/>
			<%= text_field_tag :buscar_nombre %>
		</div>
		<div class="ranking">
			<div class="table_title">Tabla de Posiciones</div>
			<%= render "buscarPuntos" %>
		</div>
		<div class="comentarios_wrap">
			<div class="table_title">Últimos Comentarios</div>
			<div id="ultimos_comentarios_container">
				<%= render "indexComentarios" %>
			</div>
		</div>
	</div>
	
<div class="clear"></div>
</div>

app/views/chinazos/new.html.erb
<h1>Ay Papá!</h1>
<%= render 'form' %>
<%= link_to 'Lista de Chinazos', action: :index %>

app/views/chinazos/show.html.erb
<div class="wrapper">
	<div class="chinazo">
		<span class="chinazoTitle">
			<%= @chinazo.nombre %>
		</span>

		<p class="chinazoContent">
			<%= auto_link(@chinazo.descripcion) { | each | each[/\.(jpg|gif|png|bmp|tif)$/] ? %Q{<img src="#{each}" width="160px" class="embeddedImage" /> } : each } %>
		</p>
		<hr />
	</div>

	<p class="buttonsBlock">		
		<% if session[:current_user_id] == @chinazo.users_id %>
		    <%= link_to 'Editar', action: :edit, id: @chinazo.id %>
		<% end %>
	    <%= link_to 'Chinazometro', action: :index %>
	</p>
	
	<p class="formBlock">
		<label class="rating">¿Qué tan feo te pareció este chinazo?</label>
		<div class="clear"></div>
		<input name="star1" title="Parcha" value="1" type="radio" class="star" <% if @chinazo.puntos_by_user(session[:current_user_id]) == 1 %> <%= 'checked="checked"' %> <% end %> />
		<input name="star1" title="Trolazo" value="2" type="radio" class="star" <% if @chinazo.puntos_by_user(session[:current_user_id]) == 2 %> <%= 'checked="checked"' %> <% end %>/>
		<input name="star1" title="Epico!" value="3" type="radio" class="star" <% if @chinazo.puntos_by_user(session[:current_user_id]) == 3 %> <%= 'checked="checked"' %> <% end %>/>
		<div class="clear"></div>
	</p>


	<%= form_tag comentarios_path, :id => 'comentariosForm', :remote => true do %>
		<%= hidden_field_tag :chinazo_id, @chinazo.id %>
		<p>
			<%= label_tag :comentario, "Tienes algo que agregar?" %>
			<%= text_area_tag :comentario, nil, :class => "comentario" %>
		</p>

			<% if flash[:errors].nil? == false %>
				<div class='errors'><%= flash[:errors] %></div>
			<% end %>
		<p>
			<%= label_tag 'Comentar', nil, :onclick => "$('#comentariosForm').submit();", :class => :btnComentario %>
		</p>
	<% end %>

	<div class="clear"></div>
	<div id="comentarios_container">
		<%= render :partial => 'comentario/index' %>
	</div>
</div>